services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: UTC
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network

  server:
    build: ./backend
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - ./backend/uploads/images:/app/uploads/images


  client:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app_network


volumes:
  db_data:

networks:
  app_network:
    driver: bridge